MAIN_LAYOUT = "main-layout"
MAIN_HEADER = "main-header"
SEARCH_BAR = "search-bar"
SEARCH_INPUT = "search-input"
SEARCH_BUTTON = "search-button"
SEARCH_ERROR_MESSAGE = "search-error-message"
ARTICLE_MATRICS = "article-matrics"
ARTICLE_MATRICS_CONTAINER = "article-matrics-container"
COMPARSION_GRAPH = "comparison-graph"
COMPARISON_GRAPH_CONTAINER = "comparison-graph-container"

GLOBAL_MATRICS = "global-metrics"
ACTIVITY_TIMELINE = "activity-timeline"
EDITS_BY_HOUR = "edits-by-hour"
TOP_ARTICLES_TABLE = "top-articles-table"
ERROR_MESSAGE = "error-message"
USERNAME_INPUT = "username-input"